# action.yml
name: "ll-builder-build"
description: "linyaps builder action"
author: myml
inputs:
  file:
    description: "linglong.yaml file path"
    default: "linglong.yaml"
    required: true
  format:
    description: "layer or uab"
    default: "layer"
    required: true

branding:
  icon: align-center
  color: "white"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        echo "deb [trusted=yes] https://ppa.linyaps.org.cn/release/Ubuntu_24.04/ ./" | sudo tee /etc/apt/sources.list.d/linglong.list
        sudo apt update
        sudo apt-get install -y --no-install-recommends linglong-builder linglong-box

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/linglong-builder
        key: linglong-builder-${{ hashFiles(inputs.file) }}
        restore-keys: |
          linglong-builder-
          Linux-linglong-builder-

    - name: Build
      shell: bash
      run: |
        ll-builder --version
        echo "enable mirror"
        ll-builder repo enable-mirror stable
        echo "mirror list"
        curl https://mirror-repo-linglong.deepin.com/api/v2/mirrors/stable
        echo "cache list"
        ll-builder list
        export LINYAPS_BACKTRACE=true
        export LINYAPS_LOG_LEVEL=debug
        ll-builder build

    - name: Export Layer
      if: ${{ inputs.format == 'layer' }}
      shell: bash
      run: ll-builder export --layer

    - name: Export UAB
      if: ${{ inputs.format == 'uab' }}
      shell: bash
      run: ll-builder export
